{
 "title": "Patch Status - satellite",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "LIFECYCLE",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: \"foreman\", tag: \"lifecycle\")"
   }
  ]
 },
 "panels": [
  {
   "title": "REGISTERED MACHINES",
   "type": "stat",
   "description": "Registered machines on Satellite",
   "gridPos": { "h": 7, "w": 12, "x": 1, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"foreman\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"patchs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalmachines\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"total\")"
    }
   ]
  },
  {
   "title": "Security - Pending updates per machine",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"foreman\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"patchs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"security\")\r\n  |> filter(fn: (r) => r[\"lifecycle\"] == \"${LIFECYCLE}\")"
    }
   ]
  },
  {
   "title": "MACHINES - PENDING UPDATE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"foreman\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"patchs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalmachines\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"security\")"
    }
   ]
  },
  {
   "title": "MACHINES - PENDING UPDATE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"foreman\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"patchs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalmachines\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"bugfix\")"
    }
   ]
  },
  {
   "title": "MACHINES - PENDING UPDATE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"foreman\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"patchs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalmachines\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"enhancement\")"
    }
   ]
  },
  {
   "title": "Bugfix- Pending updates per machine",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"foreman\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"patchs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bugfix\")\r\n  |> filter(fn: (r) => r[\"lifecycle\"] == \"${LIFECYCLE}\")"
    }
   ]
  },
  {
   "title": "MACHINES - UP TO DATE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"foreman\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"patchs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalmachines\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"total\" or r[\"type\"] == \"security\")"
    }
   ]
  },
  {
   "title": "MACHINES - UP TO DATE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"foreman\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"patchs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalmachines\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"total\" or r[\"type\"] == \"bugfix\")"
    }
   ]
  },
  {
   "title": "MACHINES - UP TO DATE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"foreman\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"patchs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalmachines\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"total\" or r[\"type\"] == \"enhancement\")"
    }
   ]
  },
  {
   "title": "Enhancement - Pending updates per machine",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"foreman\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"patchs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"enhancement\")\r\n  |> filter(fn: (r) => r[\"lifecycle\"] == \"${LIFECYCLE}\")"
    }
   ]
  },
  {
   "title": "Machines - Pending updates",
   "type": "timeseries",
   "description": "Timeline pending updates machines",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"foreman\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"patchs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalmachines\") "
    }
   ]
  }
 ]
}